test pipeline

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -1,106 +1,189 @@
-# Only manual triggers
-trigger: none
-pr: none
-
-pool:
-  vmImage: 'ubuntu-20.04'
-
-parameters:
-  - name: environment
-    displayName: Target Environment
-    type: string
-    default: uat
-    values:
-      - dev
-      - uat
-      - prod
+# Azure DevOps pipeline to release a new version and deploy to production.
 
 variables:
+  NAMESPACE: 'payments'
   MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
   MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
   BUILD_NUMBER: $(Build.BuildNumber)
-  imageRepository: 'cgn-onboarding-portal-backend'
-  ${{ if eq(parameters['environment'], 'dev') }}:
-    dockerRegistryServiceConnection: iodreminderacr
-    dockerNamespace: iodreminderacr.azurecr.io
-    connectedServiceName: DEV-IO
-    webAppName: io-d-reminder-payment-updater   
-  ${{ if eq(parameters['environment'], 'uat') }}:
-    dockerRegistryServiceConnection: $(UAT_CONTAINER_REGISTRY)
-    dockerNamespace: microserviceuarc.azurecr.io
-    connectedServiceName: $(UAT_AZURE_SUBSCRIPTION)
-    webAppName: $(UAT_WEB_APP_NAME)
-  ${{ if eq(parameters['environment'], 'prod') }}:
-    dockerRegistryServiceConnection: $(PROD_CONTAINER_REGISTRY)
-    dockerNamespace: microserviceparc.azurecr.io
-    connectedServiceName: $(PROD_AZURE_SUBSCRIPTION)
-    webAppName: $(PROD_WEB_APP_NAME)
-steps:
-  - task: Bash@3
-    displayName: Check Version and Branch
-    inputs:
-      targetType: 'inline'
-      script: |
-        version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
-        branch="$(Build.SourceBranch)"
-        if [[ "$branch" != "refs/heads/master" && ! "$branch" =~ "refs/tags/.*" && "${{ parameters.environment }}" == "prod" ]]; then
-           echo "Deploy branch $branch is not allowed."
-           exit 1
-        fi
-        if [[ "$version" == *SNAPSHOT && "${{ parameters.environment }}" == "prod" ]]; then
-           echo "Version $version is not allowed."
-           exit 1
-        fi
-      failOnStderr: true
+  DOCKER_IMAGE: 'io-pagopa-payment-updater-ms'
 
-  - task: Cache@2
-    inputs:
-      key: 'maven | "$(Agent.OS)" | pom.xml'
-      restoreKeys: |
-        maven | "$(Agent.OS)"
-        maven
-      path: $(MAVEN_CACHE_FOLDER)
-    displayName: Cache Maven local repo
+parameters:
+  - name: 'RELEASE_SEMVER'
+    displayName: 'When packing a release, define the version bump to apply'
+    type: string
+    values:
+      - major
+      - minor
+      - patch
+    default: minor
+  - name: 'FORCE_REPLACE_DOCKER_IMAGE'
+    displayName: 'Force the existing docker image to be replaced'
+    type: boolean
+    default: False
+    values:
+      - False
+      - True
 
-  - task: Maven@3
-    inputs:
-      mavenPomFile: 'pom.xml'
-      mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
-      javaHomeOption: 'JDKVersion'
-      jdkVersionOption: '1.11'
-      jdkArchitectureOption: 'x64'
-      publishJUnitResults: true
-      testResultsFiles: '**/surefire-reports/TEST-*.xml'
-      goals: 'package'
-      sonarQubeRunAnalysis: false
+# Only manual activations are intended
+trigger: none
+pr: none
 
-  - task: Bash@3
-    displayName: Get POM version
-    name: getpomversion
-    inputs:
-      targetType: 'inline'
-      script: |
-        version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
-        echo "##vso[task.setvariable variable=outputpomversion;isOutput=true]$version"
-      failOnStderr: true
+# resources:
+#   repositories:
+#     - repository: pagopaCommons
+#       type: github
+#       name: pagopa/azure-pipeline-templates
+#       ref: refs/tags/v19
+#       endpoint: 'io-azure-devops-github-ro'
 
-  - task: Docker@2
-    displayName: Build and push an image to container registry
-    inputs:
-      containerRegistry: '$(dockerRegistryServiceConnection)'
-      repository: '$(imageRepository)'
-      command: 'buildAndPush'
-      tags: |
-        $(Build.BuildId)
-        latest
-        $(getpomversion.outputpomversion)
+pool:
+  vmImage: 'ubuntu-latest'
 
-  - task: AzureRMWebAppDeployment@4
-    displayName: Azure App Service Deploy
-    inputs:
-      appType: webAppContainer
-      ConnectedServiceName: '$(connectedServiceName)'
-      WebAppName: '$(webAppName)'
-      DockerNamespace: '$(dockerNamespace)'
-      DockerRepository: '$(imageRepository)'
-      DockerImageTag: '$(Build.BuildId)'
+stages:
+  # Build
+  - stage: Build
+    #dependsOn:
+    #  - Release
+    jobs:
+      - job: 'Build'
+        steps:
+          - task: Bash@3
+            displayName: Check Version and Branch
+            inputs:
+              targetType: 'inline'
+              script: |
+                version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
+                branch="$(Build.SourceBranch)"
+                if [[ "$branch" != "refs/heads/master" && ! "$branch" =~ "refs/tags/.*" && "${{ parameters.environment }}" == "prod" ]]; then
+                  echo "Deploy branch $branch is not allowed."
+                  exit 1
+                fi
+                if [[ "$version" == *SNAPSHOT && "${{ parameters.environment }}" == "prod" ]]; then
+                  echo "Version $version is not allowed."
+                  exit 1
+                fi
+              failOnStderr: true
+
+          - task: Cache@2
+            inputs:
+              key: 'maven | "$(Agent.OS)" | pom.xml'
+              restoreKeys: |
+                maven | "$(Agent.OS)"
+                maven
+              path: $(MAVEN_CACHE_FOLDER)
+            displayName: Cache Maven local repo
+
+          - task: Maven@3
+            inputs:
+              mavenPomFile: 'pom.xml'
+              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
+              javaHomeOption: 'JDKVersion'
+              jdkVersionOption: '1.11'
+              jdkArchitectureOption: 'x64'
+              publishJUnitResults: true
+              testResultsFiles: '**/surefire-reports/TEST-*.xml'
+              goals: 'package'
+              sonarQubeRunAnalysis: false
+
+          - task: Bash@3
+            displayName: Get POM version
+            name: getpomversion
+            inputs:
+              targetType: 'inline'
+              script: |
+                version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
+                echo "##vso[task.setvariable variable=outputpomversion;isOutput=true]$version"
+              failOnStderr: true
+
+          - task: Docker@2
+            displayName: 'docker login'
+            inputs:
+              containerRegistry: 'io-p-payments-acr-docker-registry-prod'
+              command: 'login'
+          - task: Bash@3
+            displayName: 'docker build and push (force)'
+            condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, True))
+            inputs:
+              targetType: 'inline'
+              script: |
+                echo "the parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, start build and push"
+                docker build -t iopcommonacr.azurecr.io/$(DOCKER_IMAGE):$(Build.BuildId) .
+                docker build -t iopcommonacr.azurecr.io/$(DOCKER_IMAGE):$(getpomversion.outputpomversion) .
+                docker build -t iopcommonacr.azurecr.io/$(DOCKER_IMAGE):latest .
+                docker push iopcommonacr.azurecr.io/$(DOCKER_IMAGE):$(Build.BuildId)
+                docker push iopcommonacr.azurecr.io/$(DOCKER_IMAGE):$(getpomversion.outputpomversion)
+                docker push iopcommonacr.azurecr.io/$(DOCKER_IMAGE):latest
+          - task: Bash@3
+            displayName: 'docker build and push'
+            condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, False))
+            inputs:
+              targetType: 'inline'
+              script: |
+                # docker will return 0 on success or 1 on failure.
+                docker manifest inspect iopcommonacr.azurecr.io/$(DOCKER_IMAGE):latest > /dev/null
+
+                if [ $? -eq 0 ]; then
+                  echo "docker image already exists in the registry, skip build and push"
+                else
+                  echo "docker image does not exist in the registry, start build and push"
+                  docker build -t iopcommonacr.azurecr.io/$(DOCKER_IMAGE):$(Build.BuildId) .
+                  docker build -t iopcommonacr.azurecr.io/$(DOCKER_IMAGE):$(getpomversion.outputpomversion) .
+                  docker build -t iopcommonacr.azurecr.io/$(DOCKER_IMAGE):latest .
+                  docker push iopcommonacr.azurecr.io/$(DOCKER_IMAGE):$(Build.BuildId)
+                  docker push iopcommonacr.azurecr.io/$(DOCKER_IMAGE):$(getpomversion.outputpomversion)
+                  docker push iopcommonacr.azurecr.io/$(DOCKER_IMAGE):latest
+                fi
+
+  - stage: 'Serving_helm'
+    displayName: 'Serving_Helm'
+    dependsOn: Build
+    jobs:
+      - job: Serving_helm
+        displayName: Serving_helm
+        steps:
+          - task: PublishPipelineArtifact@1
+            displayName: 'Publish Artifact manifests'
+            condition: succeeded()
+            inputs:
+              targetPath: '$(Build.Repository.LocalPath)/helm'
+              artifact: 'helm'
+              publishLocation: 'pipeline'
+
+  - stage: 'Deploy'
+    dependsOn: 'Serving_helm'
+    jobs:
+      - deployment: 'Deploy'
+        pool:
+          name: io-prod-linux
+        environment: PROD
+        strategy:
+          runOnce:
+            deploy:
+              steps:
+                - download: none
+                - task: DownloadPipelineArtifact@2
+                  inputs:
+                    buildType: 'current'
+                    artifactName: 'helm'
+                    targetPath: '$(Pipeline.Workspace)/helm'
+                - task: Bash@3
+                  displayName: 'prepare helm'
+                  inputs:
+                    targetType: 'inline'
+                    script: |
+                      helm repo add microservice-chart https://pagopa.github.io/aks-microservice-chart-blueprint
+                      helm dep build $(Pipeline.Workspace)/helm
+                - task: HelmDeploy@0
+                  displayName: Helm upgrade
+                  inputs:
+                    kubernetesServiceEndpoint: io-payments-aks-weu-beta
+                    namespace: $(NAMESPACE)
+                    command: upgrade
+                    chartType: filepath
+                    chartPath: $(Pipeline.Workspace)/helm
+                    chartName: $(DOCKER_IMAGE)
+                    releaseName: $(DOCKER_IMAGE)
+                    valueFile: '$(Pipeline.Workspace)/helm/values-beta.yaml'
+                    install: true
+                    waitForExecution: true
+                    arguments: '--timeout 5m0s'
