Update deploy-pipelines.yml for Azure Pipelines

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -125,162 +125,162 @@ stages:
                   echo "We assume this reference to be a valid release: $(Build.SourceBranch). Therefore, there is no need to bundle a new release."
                 displayName: 'Skip release bundle'
 
-  # Build
-  - stage: Build
-    dependsOn: Release
-    jobs:
-      - job: 'Build'
-        steps:
-          # - task: Bash@3
-          #   displayName: Check Version and Branch
-          #   inputs:
-          #     targetType: 'inline'
-          #     script: |
-          #       version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
-          #       branch="$(Build.SourceBranch)"
-          #       if [[ "$branch" != "refs/heads/master" && ! "$branch" =~ "refs/tags/.*" && "${{ parameters.environment }}" == "prod" ]]; then
-          #         echo "Deploy branch $branch is not allowed."
-          #         exit 1
-          #       fi
-          #       if [[ "$version" == *SNAPSHOT && "${{ parameters.environment }}" == "prod" ]]; then
-          #         echo "Version $version is not allowed."
-          #         exit 1
-          #       fi
-          #     failOnStderr: true
+  # # Build
+  # - stage: Build
+  #   dependsOn: Release
+  #   jobs:
+  #     - job: 'Build'
+  #       steps:
+  #         # - task: Bash@3
+  #         #   displayName: Check Version and Branch
+  #         #   inputs:
+  #         #     targetType: 'inline'
+  #         #     script: |
+  #         #       version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
+  #         #       branch="$(Build.SourceBranch)"
+  #         #       if [[ "$branch" != "refs/heads/master" && ! "$branch" =~ "refs/tags/.*" && "${{ parameters.environment }}" == "prod" ]]; then
+  #         #         echo "Deploy branch $branch is not allowed."
+  #         #         exit 1
+  #         #       fi
+  #         #       if [[ "$version" == *SNAPSHOT && "${{ parameters.environment }}" == "prod" ]]; then
+  #         #         echo "Version $version is not allowed."
+  #         #         exit 1
+  #         #       fi
+  #         #     failOnStderr: true
 
-          - task: Bash@3
-            displayName: Get POM version
-            name: getpomversion
-            inputs:
-              targetType: 'inline'
-              script: |
-                version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
-                echo "##vso[task.setvariable variable=outputpomversion;isOutput=true]$version"
-              failOnStderr: true
+  #         - task: Bash@3
+  #           displayName: Get POM version
+  #           name: getpomversion
+  #           inputs:
+  #             targetType: 'inline'
+  #             script: |
+  #               version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
+  #               echo "##vso[task.setvariable variable=outputpomversion;isOutput=true]$version"
+  #             failOnStderr: true
 
-          - task: Docker@2
-            displayName: 'docker login'
-            inputs:
-              containerRegistry: 'io-p-payments-acr-docker-registry-prod'
-              command: 'login'
-          - task: Bash@3
-            displayName: 'docker build and push (force)'
-            condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, True))
-            inputs:
-              targetType: 'inline'
-              script: |
-                echo "[INFO] the parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, start build and push"
-                docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId) .
-                docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion) .
-                docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest .
-                docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId)
-                docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion)
-                docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest
-          - task: Bash@3
-            displayName: 'docker build and push'
-            condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, False))
-            inputs:
-              targetType: 'inline'
-              script: |
-                # docker will return 0 on success or 1 on failure.
-                docker manifest inspect $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest > /dev/null
+  #         - task: Docker@2
+  #           displayName: 'docker login'
+  #           inputs:
+  #             containerRegistry: 'io-p-payments-acr-docker-registry-prod'
+  #             command: 'login'
+  #         - task: Bash@3
+  #           displayName: 'docker build and push (force)'
+  #           condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, True))
+  #           inputs:
+  #             targetType: 'inline'
+  #             script: |
+  #               echo "[INFO] the parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, start build and push"
+  #               docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId) .
+  #               docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion) .
+  #               docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest .
+  #               docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId)
+  #               docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion)
+  #               docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest
+  #         - task: Bash@3
+  #           displayName: 'docker build and push'
+  #           condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, False))
+  #           inputs:
+  #             targetType: 'inline'
+  #             script: |
+  #               # docker will return 0 on success or 1 on failure.
+  #               docker manifest inspect $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest > /dev/null
 
-                if [ $? -eq 0 ]; then
-                  echo "[INFO] docker image already exists in the registry, skip build and push"
-                else
-                  echo "[INFO] docker image does not exist in the registry, start build and push"
-                  docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId) .
-                  docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion) .
-                  docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest .
-                  docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId)
-                  docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion)
-                  docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest
-                fi
+  #               if [ $? -eq 0 ]; then
+  #                 echo "[INFO] docker image already exists in the registry, skip build and push"
+  #               else
+  #                 echo "[INFO] docker image does not exist in the registry, start build and push"
+  #                 docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId) .
+  #                 docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion) .
+  #                 docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest .
+  #                 docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId)
+  #                 docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion)
+  #                 docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest
+  #               fi
 
-  - stage: 'Serving_helm'
-    displayName: 'Serving_Helm'
-    dependsOn: Build
-    jobs:
-      - job: Serving_helm
-        displayName: Serving_helm
-        steps:
-          - task: PublishPipelineArtifact@1
-            displayName: 'Publish Artifact manifests'
-            condition: succeeded()
-            inputs:
-              targetPath: '$(Build.Repository.LocalPath)/helm'
-              artifact: 'helm'
-              publishLocation: 'pipeline'
+  # - stage: 'Serving_helm'
+  #   displayName: 'Serving_Helm'
+  #   dependsOn: Build
+  #   jobs:
+  #     - job: Serving_helm
+  #       displayName: Serving_helm
+  #       steps:
+  #         - task: PublishPipelineArtifact@1
+  #           displayName: 'Publish Artifact manifests'
+  #           condition: succeeded()
+  #           inputs:
+  #             targetPath: '$(Build.Repository.LocalPath)/helm'
+  #             artifact: 'helm'
+  #             publishLocation: 'pipeline'
 
-  - stage: 'Deploy'
-    dependsOn: 'Serving_helm'
-    jobs:
-      - deployment: 'Deploy'
-        pool:
-          name: io-prod-linux
-        environment: PROD
-        strategy:
-          runOnce:
-            deploy:
-              steps:
-                - download: none
-                - task: DownloadPipelineArtifact@2
-                  inputs:
-                    buildType: 'current'
-                    artifactName: 'helm'
-                    targetPath: '$(Pipeline.Workspace)/helm'
-                - task: Bash@3
-                  displayName: 'prepare helm'
-                  inputs:
-                    targetType: 'inline'
-                    script: |
-                      helm repo add microservice-chart https://pagopa.github.io/aks-microservice-chart-blueprint
-                      helm dep build $(Pipeline.Workspace)/helm
-                - task: HelmDeploy@0
-                  displayName: Helm upgrade
-                  condition: and(succeeded(), eq(${{ parameters.ENVIRONMENT_WEU_BETA }}, True))
-                  inputs:
-                    kubernetesServiceEndpoint: $(KUBERNETES_SERVICE_CONN_WEU_BETA)
-                    namespace: $(NAMESPACE)
-                    command: upgrade
-                    chartType: filepath
-                    chartPath: $(Pipeline.Workspace)/helm
-                    chartName: $(DOCKER_IMAGE_NAME)
-                    releaseName: $(DOCKER_IMAGE_NAME)
-                    valueFile: '$(Pipeline.Workspace)/helm/values-beta.yaml'
-                    install: true
-                    waitForExecution: true
-                    arguments: '--timeout 5m0s'
-                    overrideValues: microservice-chart.image.tag=$(Build.BuildId)
-                - task: HelmDeploy@0
-                  displayName: Helm upgrade
-                  condition: and(succeeded(), eq(${{ parameters.ENVIRONMENT_WEU_PROD_01 }}, True))
-                  inputs:
-                    kubernetesServiceEndpoint: $(KUBERNETES_SERVICE_CONN_WEU_PROD_01)
-                    namespace: $(NAMESPACE)
-                    command: upgrade
-                    chartType: filepath
-                    chartPath: $(Pipeline.Workspace)/helm
-                    chartName: $(DOCKER_IMAGE_NAME)
-                    releaseName: $(DOCKER_IMAGE_NAME)
-                    valueFile: '$(Pipeline.Workspace)/helm/values-prod01.yaml'
-                    install: true
-                    waitForExecution: true
-                    arguments: '--timeout 5m0s'
-                    overrideValues: microservice-chart.image.tag=$(Build.BuildId)
-                - task: HelmDeploy@0
-                  displayName: Helm upgrade
-                  condition: and(succeeded(), eq(${{ parameters.ENVIRONMENT_WEU_PROD_02 }}, True))
-                  inputs:
-                    kubernetesServiceEndpoint: $(KUBERNETES_SERVICE_CONN_WEU_PROD_02)
-                    namespace: $(NAMESPACE)
-                    command: upgrade
-                    chartType: filepath
-                    chartPath: $(Pipeline.Workspace)/helm
-                    chartName: $(DOCKER_IMAGE_NAME)
-                    releaseName: $(DOCKER_IMAGE_NAME)
-                    valueFile: '$(Pipeline.Workspace)/helm/values-prod02.yaml'
-                    install: true
-                    waitForExecution: true
-                    arguments: '--timeout 5m0s'
-                    overrideValues: microservice-chart.image.tag=$(Build.BuildId)
+  # - stage: 'Deploy'
+  #   dependsOn: 'Serving_helm'
+  #   jobs:
+  #     - deployment: 'Deploy'
+  #       pool:
+  #         name: io-prod-linux
+  #       environment: PROD
+  #       strategy:
+  #         runOnce:
+  #           deploy:
+  #             steps:
+  #               - download: none
+  #               - task: DownloadPipelineArtifact@2
+  #                 inputs:
+  #                   buildType: 'current'
+  #                   artifactName: 'helm'
+  #                   targetPath: '$(Pipeline.Workspace)/helm'
+  #               - task: Bash@3
+  #                 displayName: 'prepare helm'
+  #                 inputs:
+  #                   targetType: 'inline'
+  #                   script: |
+  #                     helm repo add microservice-chart https://pagopa.github.io/aks-microservice-chart-blueprint
+  #                     helm dep build $(Pipeline.Workspace)/helm
+  #               - task: HelmDeploy@0
+  #                 displayName: Helm upgrade
+  #                 condition: and(succeeded(), eq(${{ parameters.ENVIRONMENT_WEU_BETA }}, True))
+  #                 inputs:
+  #                   kubernetesServiceEndpoint: $(KUBERNETES_SERVICE_CONN_WEU_BETA)
+  #                   namespace: $(NAMESPACE)
+  #                   command: upgrade
+  #                   chartType: filepath
+  #                   chartPath: $(Pipeline.Workspace)/helm
+  #                   chartName: $(DOCKER_IMAGE_NAME)
+  #                   releaseName: $(DOCKER_IMAGE_NAME)
+  #                   valueFile: '$(Pipeline.Workspace)/helm/values-beta.yaml'
+  #                   install: true
+  #                   waitForExecution: true
+  #                   arguments: '--timeout 5m0s'
+  #                   overrideValues: microservice-chart.image.tag=$(Build.BuildId)
+  #               - task: HelmDeploy@0
+  #                 displayName: Helm upgrade
+  #                 condition: and(succeeded(), eq(${{ parameters.ENVIRONMENT_WEU_PROD_01 }}, True))
+  #                 inputs:
+  #                   kubernetesServiceEndpoint: $(KUBERNETES_SERVICE_CONN_WEU_PROD_01)
+  #                   namespace: $(NAMESPACE)
+  #                   command: upgrade
+  #                   chartType: filepath
+  #                   chartPath: $(Pipeline.Workspace)/helm
+  #                   chartName: $(DOCKER_IMAGE_NAME)
+  #                   releaseName: $(DOCKER_IMAGE_NAME)
+  #                   valueFile: '$(Pipeline.Workspace)/helm/values-prod01.yaml'
+  #                   install: true
+  #                   waitForExecution: true
+  #                   arguments: '--timeout 5m0s'
+  #                   overrideValues: microservice-chart.image.tag=$(Build.BuildId)
+  #               - task: HelmDeploy@0
+  #                 displayName: Helm upgrade
+  #                 condition: and(succeeded(), eq(${{ parameters.ENVIRONMENT_WEU_PROD_02 }}, True))
+  #                 inputs:
+  #                   kubernetesServiceEndpoint: $(KUBERNETES_SERVICE_CONN_WEU_PROD_02)
+  #                   namespace: $(NAMESPACE)
+  #                   command: upgrade
+  #                   chartType: filepath
+  #                   chartPath: $(Pipeline.Workspace)/helm
+  #                   chartName: $(DOCKER_IMAGE_NAME)
+  #                   releaseName: $(DOCKER_IMAGE_NAME)
+  #                   valueFile: '$(Pipeline.Workspace)/helm/values-prod02.yaml'
+  #                   install: true
+  #                   waitForExecution: true
+  #                   arguments: '--timeout 5m0s'
+  #                   overrideValues: microservice-chart.image.tag=$(Build.BuildId)
